name: run-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  basic-checks:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Run go vet
        run: go vet ./...
      - name: Run golint
        run: golint ./...
      - name: Run gofmt
        run: gofmt -s -l .
      - name: Run errcheck
        run: |
          go get github.com/kisielk/errcheck
          errcheck ./...
      - name: Run staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
